name: Deploy to App Store

on:
  push:
    branches:
      - main  # O workflow é disparado quando há um push na branch 'main'

jobs:
  pre-install:
    uses: wellingtonrptech/workflow-templates/.github/workflows/pre-install.yaml@main

  build:
    needs: pre-install
    uses: wellingtonrptech/workflow-templates/.github/workflows/build.yaml@main

  deploy:
    needs: build
    uses: wellingtonrptech/workflow-templates/.github/workflows/deploy.yaml@main