name: Deploy

on:
  push:
    branches:
      - main  # The workflow is triggered on a push to the 'main' branch

jobs:
  pre-install:
    uses: wellingtonrptech/workflow-templates/.github/workflows/pre-install.yaml@main

  build:
    needs: pre-install
    uses: wellingtonrptech/workflow-templates/.github/workflows/build.yaml@main

  deploy:
    needs: build
    uses: wellingtonrptech/workflow-templates/.github/workflows/deploy.yaml@main
